# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: simple.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='simple.proto',
  package='com.example.demorsocketrpc',
  syntax='proto3',
  serialized_pb=_b('\n\x0csimple.proto\x12\x1a\x63om.example.demorsocketrpc\x1a\x1bgoogle/protobuf/empty.proto\"\'\n\rSimpleRequest\x12\x16\n\x0erequestMessage\x18\x01 \x01(\t\")\n\x0eSimpleResponse\x12\x17\n\x0fresponseMessage\x18\x01 \x01(\t2x\n\rSimpleService\x12g\n\x0cRequestReply\x12).com.example.demorsocketrpc.SimpleRequest\x1a*.com.example.demorsocketrpc.SimpleResponse\"\x00\x42\x32\n\x1a\x63om.example.demorsocketrpcB\x12SimpleServiceProtoP\x01\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_SIMPLEREQUEST = _descriptor.Descriptor(
  name='SimpleRequest',
  full_name='com.example.demorsocketrpc.SimpleRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='requestMessage', full_name='com.example.demorsocketrpc.SimpleRequest.requestMessage', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=112,
)


_SIMPLERESPONSE = _descriptor.Descriptor(
  name='SimpleResponse',
  full_name='com.example.demorsocketrpc.SimpleResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='responseMessage', full_name='com.example.demorsocketrpc.SimpleResponse.responseMessage', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=114,
  serialized_end=155,
)

DESCRIPTOR.message_types_by_name['SimpleRequest'] = _SIMPLEREQUEST
DESCRIPTOR.message_types_by_name['SimpleResponse'] = _SIMPLERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SimpleRequest = _reflection.GeneratedProtocolMessageType('SimpleRequest', (_message.Message,), dict(
  DESCRIPTOR = _SIMPLEREQUEST,
  __module__ = 'simple_pb2'
  # @@protoc_insertion_point(class_scope:com.example.demorsocketrpc.SimpleRequest)
  ))
_sym_db.RegisterMessage(SimpleRequest)

SimpleResponse = _reflection.GeneratedProtocolMessageType('SimpleResponse', (_message.Message,), dict(
  DESCRIPTOR = _SIMPLERESPONSE,
  __module__ = 'simple_pb2'
  # @@protoc_insertion_point(class_scope:com.example.demorsocketrpc.SimpleResponse)
  ))
_sym_db.RegisterMessage(SimpleResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\032com.example.demorsocketrpcB\022SimpleServiceProtoP\001'))

_SIMPLESERVICE = _descriptor.ServiceDescriptor(
  name='SimpleService',
  full_name='com.example.demorsocketrpc.SimpleService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=157,
  serialized_end=277,
  methods=[
  _descriptor.MethodDescriptor(
    name='RequestReply',
    full_name='com.example.demorsocketrpc.SimpleService.RequestReply',
    index=0,
    containing_service=None,
    input_type=_SIMPLEREQUEST,
    output_type=_SIMPLERESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SIMPLESERVICE)

DESCRIPTOR.services_by_name['SimpleService'] = _SIMPLESERVICE

# @@protoc_insertion_point(module_scope)
